site_name: Mahendra Pawar Agents Documentation
theme:
  name: rtd-dropdown
nav:
  - Getting Started: index.md
  - Agents:
    - Agent Overview: agent_overview/index.md
  - Prompt Template: prompt_template.md
