site_name: Mahendra Pawar Agents Documentation
theme:
  name: dracula
  features:
    - navigation.tabs
    - navigation.expand
    - content.code.copy
  palette:
    - scheme: slate
      primary: indigo
      accent: purple

nav:
  - Home: index.md
  - User Guide:
    - Getting Started: user-guide/getting-started.md
    - Stateless Agent: user-guide/stateless-agent.md
    - Summarizer Agent: user-guide/summarizer-agent.md
    - Virtual Assistant Agent: user-guide/virtual-assistant-agent.md
  - API Reference:
    - Core Modules: api-reference/core-modules.md
    - Stateless Agent: api-reference/stateless-agent.md
    - Summarizer Agent: api-reference/summarizer-agent.md
    - Virtual Assistant Agent: api-reference/virtual-assistant-agent.md
